INSERT INTO higher_level_sub_category (id, parent_id, name, description)
VALUES
(1, 4, 'Bicycles', ''),
(2, 4, 'Motor Vehicle ', ''),
(3, 4, 'Motor Cycles', ''),
(4, 4, 'Water Craft', ''),
(5, 4, 'Air Craft', ''),
(6, 2, 'Houses', ''),
(7, 2, 'Cottage', ''),
(8, 2, 'Flat', ''),
(9, 2, 'Lodge', ''),
(10, 3, 'BUSINESS AND FINANCE', ''),
(11, 3, 'COMPUTERS AND TECHNOLOGY', ''),
(12, 3, 'CONSTRUCTION TRADES', ''),
(13, 3, 'EDUCATION, TEACHING AND TRAINING', ''),
(14, 3, 'ENGINEERING AND ENGINEERING TECHNICIAN', ''),
(15, 3, 'FISHING, FARMING AND FORESTRY', ''),
(16, 3, 'HEALTH AND MEDICAL', ''),
(17, 3, 'HOSPITALITY, TRAVEL & TOURISM', ''),
(18, 3, 'LEGAL, CRIMINAL JUSTICE AND LAW ENFORCEMENT', ''),
(19, 3, 'MANAGEMENT', ''),
(20, 3, 'MEDIA COMMUNICATIONS AND BROADCASTING', ''),
(21, 3, 'OFFICE ADMINISTRATION AND MANAGEMENT', ''),
(22, 3, 'PRODUCTION AND MANUFACTURING', ''),
(23, 3, 'PROFESSIONAL SERVICE', ''),
(24, 3, 'PSYCHOLOGY AND COUNSELLING', ''),
(25, 3, 'INSTALLATION REPAIR AND MAINTENANCE', ''),
(26, 3, 'SALES AND MARKETING', ''),
(27, 3, 'SOCIAL AND LIFE SCIENCES', ''),
(28, 3, 'TRANSPORTATION AND MOVING', ''),
(29, 3, 'FISHING, FARMING AND FORESTRY', ''),
(30, 3, 'HEALTH AND MEDICAL', ''),
(31, 3, 'HOSPITALITY, TRAVEL & TOURISM', ''),
(32, 3, 'LEGAL, CRIMINAL JUSTICE AND LAW ENFORCEMENT', ''),
(33, 3, 'MANAGEMENT', ''),
(34, 3, 'MEDIA COMMUNICATIONS AND BROADCASTING', ''),
(35, 3, 'OFFICE ADMINISTRATION AND MANAGEMENT', ''),
(36, 3, 'PRODUCTION AND MANUFACTURING', ''),
(37, 3, 'PROFESSIONAL SERVICE', ''),
(38, 3, 'PSYCHOLOGY AND COUNSELLING', ''),
(39, 3, 'INSTALLATION REPAIR AND MAINTENANCE', ''),
(40, 3, 'SALES AND MARKETING', ''),
(41, 3, 'SOCIAL AND LIFE SCIENCES', ''),
(42, 3, 'TRANSPORTATION AND MOVING', ''),
(43, 1, 'Accounting', 'Accounting services'),
(44, 1, 'Marketing', 'Marketing Services'),
(45, 1, 'Building', 'Building Services'),
(46, 1, 'Boat', 'Boat Services'),
(47, 5, 'Agriculture Food and Drinks'),
(47, 5, 'Clothing and Fabric'),
(47, 5, 'Style, Jewellery and Watches'),
(47, 5, 'Vehicles Accessories and Parts'),
(47, 5, 'Bags'),
(47, 5, 'Shoes & Shoe Parts'),
(47, 5, 'Electronics'),
(47, 5, ''),
(47, 5, ''),