INSERT INTO product_search_field (category_id, product_class_id, name)
VALUES
(1,1,'Accounting Services'),
(1,1,'Advertising Services'),
(1,1,'Building Services'),
(1,1,'Boat Services'),
(1,1,'Bridal Services'),
(1,1,'Business Services'),
(1,1,'Car Rental Agencies'),
(1,1,'Catering Services'),
(1,1,'Children’s Services'),
(1,1,'Check-Cashing Services'),
(1,1,'Cleaning Services'),
(1,1,'Check-Cashing Services'),
(1,1,'Consulting Services'),
(1,1,'Contractor Services'),
(1,1,'Copywriting & Proof Services'),
(1,1,'Cover Letter/Resume Services'),
(1,1,'Dating Services'),
(1,1,'Decorating Services'),
(1,1,'Designing Services'),
(1,1,'DJ Businesses'),
(1,1,'Dry Cleaning & Laundry Services'),
(1,1,'Dry Cleaning Delivery'),
(1,1,'Editorial Services'),
(1,1,'Educational Services'),
(1,1,'Electrical Services'),
(1,1,'Employment Services'),
(1,1,'Environmental Services'),
(1,1,'Errand Services'),
(1,1,'Event Planning'),
(1,1,'Eye-Care Centers'),
(1,1,'Financial Services'),
(1,1,'Fitness Centers'),
(1,1,'Hair Salons'),
(1,1,'Handyman Services'),
(1,1,'Health-Care Services'),
(1,1,'Home-Improvement Services'),
(1,1,'Lawn Care & Landscaping'),
(1,1,'Limousine Services'),
(1,1,'Maintenance Services'),
(1,1,'Message Therapist'),
(1,1,'Motor Mechanic Services'),
(1,1,'Moving Services'),
(1,1,'Painting Services'),
(1,1,'Personal-Care Services'),
(1,1,'Personal Chef'),
(1,1,'Pest Control Services'),
(1,1,'Pet-Care Services'),
(1,1,'Photography Services'),
(1,1,'Plant Maintenance Services'),
(1,1,'Plumbing Services'),
(1,1,'Pool Services'),
(1,1,'Postal & Business Centers'),
(1,1,'Printing Services'),
(1,1,'Private Investigation'),
(1,1,'Property Inspection'),
(1,1,'Property Management Services'),
(1,1,'Publishing Services'),
(1,1,'Real Estate Services'),
(1,1,'Recreational Services'),
(1,1,'Referral Services'),
(1,1,'Remodeling/Renovation Services'),
(1,1,'Repair Services'),
(1,1,'Security Services'),
(1,1,'Senior Care Services'),
(1,1,'Shipping Services'),
(1,1,'Shoe Repair'),
(1,1,'Sign Stores'),
(1,1,'Staffing Services'),
(1,1,'Tanning Services'),
(1,1,'Tax Services'),
(1,1,'Tech Services'),
(1,1,'Travel Agencies'),
(1,1,'Training Businesses'),
(1,1,'Tree cutting Services'),
(1,1,'Tutoring Services'),
(1,1,'Videotaping Services'),
(1,1,'Web-Site Services'),
(1,1,'Wedding Services'),
(1,1,'Weight-Control Centers');
